/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Score4_GUI;

import Score4_AI.Game;
import Score4_AI.Sequin;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author p3120124
 */
public class Score4_Game_GridLayout extends javax.swing.JFrame {

    /**
     * Creates new form Score4_Game
     */
    private Game thisGame;
    public int time = 0;
    
    public Score4_Game_GridLayout(Game game) {
        initComponents();
        this.thisGame = game;
        this.thisGame.setJLabel(timeLiveLabel);
        this.thisGame.startGame();
        //this.playerInfoLabel.setText("It's your turn "+player.getPname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerInfoPanel = new javax.swing.JPanel();
        playerInfoLabel = new javax.swing.JLabel();
        timePanel = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        timeLiveLabel = new javax.swing.JLabel();
        columnButtons = new javax.swing.JToolBar();
        col1Button = new javax.swing.JButton();
        colSeperator1 = new javax.swing.JToolBar.Separator();
        col2Button = new javax.swing.JButton();
        colSeperator2 = new javax.swing.JToolBar.Separator();
        col3Button = new javax.swing.JButton();
        colSeperator3 = new javax.swing.JToolBar.Separator();
        col4Button = new javax.swing.JButton();
        colSeperator4 = new javax.swing.JToolBar.Separator();
        col5Button = new javax.swing.JButton();
        colSeperator5 = new javax.swing.JToolBar.Separator();
        col6Button = new javax.swing.JButton();
        colSeperator6 = new javax.swing.JToolBar.Separator();
        col7Button = new javax.swing.JButton();
        buttonsBoardSeperator = new javax.swing.JSeparator();
        infoBoardSeperator = new javax.swing.JSeparator();
        infoTimeSeperator = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        inGameMenu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        Edit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Score4");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon.png")).getImage());
        setLocation(new java.awt.Point(450, 200));
        setResizable(false);

        playerInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playerInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout playerInfoPanelLayout = new javax.swing.GroupLayout(playerInfoPanel);
        playerInfoPanel.setLayout(playerInfoPanelLayout);
        playerInfoPanelLayout.setHorizontalGroup(
            playerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        playerInfoPanelLayout.setVerticalGroup(
            playerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("Time:");

        timeLiveLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePanelLayout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeLiveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        columnButtons.setBorder(new javax.swing.border.MatteBorder(null));
        columnButtons.setFloatable(false);
        columnButtons.setRollover(true);
        columnButtons.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        col1Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col1Button.setMnemonic(KeyEvent.VK_1);
        col1Button.setText("Col1");
        col1Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col1Button.setFocusable(false);
        col1Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col1Button.setMargin(new java.awt.Insets(2, 23, 2, 18));
        col1Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        col1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col1ButtonActionPerformed(evt);
            }
        });
        columnButtons.add(col1Button);
        columnButtons.add(colSeperator1);

        col2Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col2Button.setMnemonic(KeyEvent.VK_2);
        col2Button.setText("Col2");
        col2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col2Button.setFocusable(false);
        col2Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col2Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col2Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        col2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col2ButtonActionPerformed(evt);
            }
        });
        columnButtons.add(col2Button);
        columnButtons.add(colSeperator2);

        col3Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col3Button.setMnemonic(KeyEvent.VK_3);
        col3Button.setText("Col3");
        col3Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col3Button.setFocusable(false);
        col3Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col3Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col3Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        col3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col3ButtonActionPerformed(evt);
            }
        });
        columnButtons.add(col3Button);
        columnButtons.add(colSeperator3);

        col4Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col4Button.setMnemonic(KeyEvent.VK_4);
        col4Button.setText("Col4");
        col4Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col4Button.setFocusable(false);
        col4Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col4Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col4Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        col4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col4ButtonActionPerformed(evt);
            }
        });
        columnButtons.add(col4Button);
        columnButtons.add(colSeperator4);

        col5Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col5Button.setMnemonic(KeyEvent.VK_5);
        col5Button.setText("Col5");
        col5Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col5Button.setFocusable(false);
        col5Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col5Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col5Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        col5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col5ButtonActionPerformed(evt);
            }
        });
        columnButtons.add(col5Button);
        columnButtons.add(colSeperator5);

        col6Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col6Button.setMnemonic(KeyEvent.VK_6);
        col6Button.setText("Col6");
        col6Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col6Button.setFocusable(false);
        col6Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col6Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col6Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        col6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col6ButtonActionPerformed(evt);
            }
        });
        columnButtons.add(col6Button);
        columnButtons.add(colSeperator6);

        col7Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col7Button.setMnemonic(KeyEvent.VK_7);
        col7Button.setText("Col7");
        col7Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col7Button.setFocusable(false);
        col7Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col7Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col7Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        col7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col7ButtonActionPerformed(evt);
            }
        });
        columnButtons.add(col7Button);

        infoTimeSeperator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        FileMenu.setText("File");
        inGameMenu.add(FileMenu);

        Edit.setText("Edit");
        inGameMenu.add(Edit);

        setJMenuBar(inGameMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoBoardSeperator)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoTimeSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(columnButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonsBoardSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoTimeSeperator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoBoardSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(columnButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(buttonsBoardSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void col1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col1ButtonActionPerformed
        Sequin sequin = thisGame.putSequinInPos(0, this.thisGame.getPlayer().getpIcon());
    }//GEN-LAST:event_col1ButtonActionPerformed

    private void col2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col2ButtonActionPerformed
        Sequin sequin = thisGame.putSequinInPos(1, this.thisGame.getPlayer().getpIcon());
        drawSequinInBoard(sequin);
    }//GEN-LAST:event_col2ButtonActionPerformed

    private void col3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col3ButtonActionPerformed
        Sequin sequin = thisGame.putSequinInPos(2, this.thisGame.getPlayer().getpIcon());
        drawSequinInBoard(sequin);
    }//GEN-LAST:event_col3ButtonActionPerformed

    private void col4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col4ButtonActionPerformed
        Sequin sequin = thisGame.putSequinInPos(3, this.thisGame.getPlayer().getpIcon());
        drawSequinInBoard(sequin);
    }//GEN-LAST:event_col4ButtonActionPerformed

    private void col5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col5ButtonActionPerformed
        Sequin sequin = thisGame.putSequinInPos(4, this.thisGame.getPlayer().getpIcon());
        drawSequinInBoard(sequin);
    }//GEN-LAST:event_col5ButtonActionPerformed

    private void col6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col6ButtonActionPerformed
        Sequin sequin = thisGame.putSequinInPos(5, this.thisGame.getPlayer().getpIcon());
        drawSequinInBoard(sequin);
    }//GEN-LAST:event_col6ButtonActionPerformed

    private void col7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col7ButtonActionPerformed
        Sequin sequin = thisGame.putSequinInPos(6, this.thisGame.getPlayer().getpIcon());
        drawSequinInBoard(sequin);
    }//GEN-LAST:event_col7ButtonActionPerformed
        
    private void drawSequinInBoard(Sequin sequin) {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JSeparator buttonsBoardSeperator;
    private javax.swing.JButton col1Button;
    private javax.swing.JButton col2Button;
    private javax.swing.JButton col3Button;
    private javax.swing.JButton col4Button;
    private javax.swing.JButton col5Button;
    private javax.swing.JButton col6Button;
    private javax.swing.JButton col7Button;
    private javax.swing.JToolBar.Separator colSeperator1;
    private javax.swing.JToolBar.Separator colSeperator2;
    private javax.swing.JToolBar.Separator colSeperator3;
    private javax.swing.JToolBar.Separator colSeperator4;
    private javax.swing.JToolBar.Separator colSeperator5;
    private javax.swing.JToolBar.Separator colSeperator6;
    private javax.swing.JToolBar columnButtons;
    private javax.swing.JMenuBar inGameMenu;
    private javax.swing.JSeparator infoBoardSeperator;
    private javax.swing.JSeparator infoTimeSeperator;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel playerInfoLabel;
    private javax.swing.JPanel playerInfoPanel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeLiveLabel;
    private javax.swing.JPanel timePanel;
    // End of variables declaration//GEN-END:variables

}
