/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Score4_GUI;

import java.awt.event.KeyEvent;

/**
 *
 * @author p3120124
 */
public class Score4_Game extends javax.swing.JFrame {

    /**
     * Creates new form Score4_Game
     */
    public Score4_Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        columnButtons = new javax.swing.JToolBar();
        col1Button = new javax.swing.JButton();
        colSeperator1 = new javax.swing.JToolBar.Separator();
        col2Button = new javax.swing.JButton();
        colSeperator2 = new javax.swing.JToolBar.Separator();
        col3Button = new javax.swing.JButton();
        colSeperator3 = new javax.swing.JToolBar.Separator();
        col4Button = new javax.swing.JButton();
        colSeperator4 = new javax.swing.JToolBar.Separator();
        col5Button = new javax.swing.JButton();
        colSeperator5 = new javax.swing.JToolBar.Separator();
        col6Button = new javax.swing.JButton();
        colSeperator6 = new javax.swing.JToolBar.Separator();
        col7Button = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        score4Board = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inGameMenu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        Edit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Score4");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon.png")).getImage());
        setLocation(new java.awt.Point(450, 200));
        setResizable(false);

        columnButtons.setBorder(new javax.swing.border.MatteBorder(null));
        columnButtons.setFloatable(false);
        columnButtons.setRollover(true);
        columnButtons.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        col1Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col1Button.setMnemonic(KeyEvent.VK_1);
        col1Button.setText("Col1");
        col1Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col1Button.setFocusable(false);
        col1Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col1Button.setMargin(new java.awt.Insets(2, 23, 2, 18));
        col1Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        col1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col1ButtonActionPerformed(evt);
            }
        });
        columnButtons.add(col1Button);
        columnButtons.add(colSeperator1);

        col2Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col2Button.setMnemonic(KeyEvent.VK_2);
        col2Button.setText("Col2");
        col2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col2Button.setFocusable(false);
        col2Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col2Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col2Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        columnButtons.add(col2Button);
        columnButtons.add(colSeperator2);

        col3Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col3Button.setMnemonic(KeyEvent.VK_3);
        col3Button.setText("Col3");
        col3Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col3Button.setFocusable(false);
        col3Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col3Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col3Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        columnButtons.add(col3Button);
        columnButtons.add(colSeperator3);

        col4Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col4Button.setMnemonic(KeyEvent.VK_4);
        col4Button.setText("Col4");
        col4Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col4Button.setFocusable(false);
        col4Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col4Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col4Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        columnButtons.add(col4Button);
        columnButtons.add(colSeperator4);

        col5Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col5Button.setMnemonic(KeyEvent.VK_5);
        col5Button.setText("Col5");
        col5Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col5Button.setFocusable(false);
        col5Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col5Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col5Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        columnButtons.add(col5Button);
        columnButtons.add(colSeperator5);

        col6Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col6Button.setMnemonic(KeyEvent.VK_6);
        col6Button.setText("Col6");
        col6Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col6Button.setFocusable(false);
        col6Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col6Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col6Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        columnButtons.add(col6Button);
        columnButtons.add(colSeperator6);

        col7Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        col7Button.setMnemonic(KeyEvent.VK_7);
        col7Button.setText("Col7");
        col7Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        col7Button.setFocusable(false);
        col7Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        col7Button.setMargin(new java.awt.Insets(2, 23, 2, 14));
        col7Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        columnButtons.add(col7Button);

        score4Board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Connect4Board.png"))); // NOI18N

        jLayeredPane1.setLayer(score4Board, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(621, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(score4Board)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(score4Board, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FileMenu.setText("File");
        inGameMenu.add(FileMenu);

        Edit.setText("Edit");
        inGameMenu.add(Edit);

        setJMenuBar(inGameMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(columnButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(columnButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void col1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col1ButtonActionPerformed
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/green_player.png")));
    }//GEN-LAST:event_col1ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score4_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score4_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score4_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score4_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Score4_Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton col1Button;
    private javax.swing.JButton col2Button;
    private javax.swing.JButton col3Button;
    private javax.swing.JButton col4Button;
    private javax.swing.JButton col5Button;
    private javax.swing.JButton col6Button;
    private javax.swing.JButton col7Button;
    private javax.swing.JToolBar.Separator colSeperator1;
    private javax.swing.JToolBar.Separator colSeperator2;
    private javax.swing.JToolBar.Separator colSeperator3;
    private javax.swing.JToolBar.Separator colSeperator4;
    private javax.swing.JToolBar.Separator colSeperator5;
    private javax.swing.JToolBar.Separator colSeperator6;
    private javax.swing.JToolBar columnButtons;
    private javax.swing.JMenuBar inGameMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel score4Board;
    // End of variables declaration//GEN-END:variables
}
