/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Score4_GUI;

/**
 *
 * @author p3120124
 */
public class Score4_Game extends javax.swing.JFrame {

    /**
     * Creates new form Score4_Game
     */
    public Score4_Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board_backround = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        File_menu = new javax.swing.JMenu();
        NewGame_menuItem = new javax.swing.JMenuItem();
        Exit_menuItem = new javax.swing.JMenuItem();
        Edit_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 530));
        setResizable(false);

        board_backround.setIcon(new javax.swing.ImageIcon("C:\\Users\\p3120124\\Documents\\NetBeansProjects\\AI_Score4\\AI_Score4\\Assets\\Connect4Board.png")); // NOI18N

        File_menu.setText("File");

        NewGame_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        NewGame_menuItem.setText("New Game");
        File_menu.add(NewGame_menuItem);

        Exit_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit_menuItem.setText("Exit");
        Exit_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_menuItemActionPerformed(evt);
            }
        });
        File_menu.add(Exit_menuItem);

        Menu.add(File_menu);

        Edit_menu.setText("Edit");
        Menu.add(Edit_menu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(board_backround)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(board_backround)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_menuItemActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_Exit_menuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score4_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score4_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score4_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score4_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Score4_Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit_menu;
    private javax.swing.JMenuItem Exit_menuItem;
    private javax.swing.JMenu File_menu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem NewGame_menuItem;
    private javax.swing.JLabel board_backround;
    // End of variables declaration//GEN-END:variables
}
